# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=15)),
                ('lon', models.CharField(max_length=15)),
                ('info', models.CharField(max_length=500)),
                ('msg_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
